### ISSUE TITLE
Extraneous files are being uploaded to the server

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#114]
We don't need directories like `gulpfile.js/` or `src/` on the server. All of the files are necessary just for building the public assets, we can update SFTP to ignore these things — especially since those files are all tracked by git and are available by cloning the repo.

**Comment by jeremy-farrance** [comment]
Did Josh bring this up recently? He and I were just talking about this last week or so. I was definitely feeling like there were a lot of items on the server that did not need to be there and wondering how to prune things down to only what is needed. But part of the problem is that there is automation and humans. I am sure - in a moment of unsure necessary - that I have occasionally just uploaded whole folders unnecessarily.
 
Packaging the theme is also a thing that we don't do. Other theme projects do (like nvQuickTheme). I am not suggesting we need or do that anytime soon, but it might be useful to document in a structured way, the folders and files that ARE necessary. If it is not already in place, is it possible to structure the project so that there is only 3 things:

1. a list of folders that are require on the server
2. a list of folders that are never uploaded
3. pattern of files in the root that are needed (e.g. all *.ascx, all *.css)
 
Or am I too far off topic?

**Comment by chrismlusk** [comment]
No, but it's something I've thought about a few times before. We have tons of config, source, etc. that are important to development, and just a waste of space for the server.

Because we use vscode and the sftp plugin, my thought is to just update `sftp.json` to include these:

```js
  "ignore": [
    "**/gulpfile.js/", // stuff for Gulp build pipeline
    "**/node_modules/", // all npm installed stuff
    "**/src/", // pre-compiled Sass, JS, etc.
    "**/README.md", // docs
    ".*", // all dot files (which are mainly configs)
    "package.json",
    "package-lock.json",
    "real-favicon-generator.json",
    "webpack.config.js",
  ],
```

There might be opportunities to further decouple the dev-required things (e.g., source files) from the folder/files needed to package a theme. We can continue to explore. Maybe we can restructure at the same time we upgrade to Bootstrap v5?

**Comment by jeremy-farrance** [comment]
I guess I can test it, but that means on-save, sftp won't upload it, but will it prevent a human from uploading it manually?

**Comment by chrismlusk** [comment]
Nope, there's nothing preventing anyone from manually uploading junk. It's the fatal flaw in everything: human beings.
