### ISSUE TITLE
Add sidebar pane to Main layout template

### ISSUE THREAD

**Issue by Accuraty** [chrismlusk/accuraty-templates#27]
Since we are gearing towards general purpose, I find it hard to work on a big project like PDEG without having the usual/expected skin template (ascx) with a sidebar. Am I wrong that they used to exist in `accuraty-templates`? If not, we need just need to add a super-simple one with a top ContentPane (12)
LeftContentPane (9) | AsidePane (3)

**Comment by chrismlusk** [comment]
Sure. I've always kept it with one pane and added new ones as needed, but that's reasonable now that the project is bigger and in use by multiple people.

**Comment by chrismlusk** [comment]
@Accuraty, this addition will sort of touch the following issues/questions:

- https://github.com/chrismlusk/accuraty-templates/issues/12#issuecomment-471332287
- https://github.com/Accuraty/PDEG/pull/5#discussion_r273054866

Let me know if you have any thoughts about either. I'm inclined to definitely incorporate the first one, since not every project or page would use all three panes (content, sidebar, left/right).
