### ISSUE TITLE
Problem with "NoTitle" containers?

### ISSUE THREAD

**Issue by chrismlusk** [chrismlusk/accuraty-templates#6]
Jeremy brought up an issue with using "NoTitle" containers on DNN sites.

The problem seems to be that we want a way for site managers to see more info about the modules when they are editing a page. Jeremy suggested we should make container titles visible while in edit mode so site managers have an easier time knowing what to do / where to go.

My initial pushback is that the use of container titles is dependent on layout design and context. In short, sometimes we want to use titles; other times we don't. So making all container title hidden in normal mode and visible in edit mode won't work. We'd still end up creating multiple containers.

Jeremy mentioned a "correct way" to turn off container titles, but I need more information about what that means and how we could use that to accomplish our goals.

@Accuraty, any clarifications and/or thoughts to add?

**Comment by chrismlusk** [comment]
@Accuraty, can you weigh in?

**Comment by Accuraty** [comment]
DNN has a module setting named Display Container. The idea used to be that you could inject the module with no wrapper (container) and therefore would not see the title or any other 'code' from the container, but you would get all of the output of the module. Though you'd lose your wrapper and any styling, this was one way to turn off the module's title when it wasn't wanted (due to design).

Above is an aside. Aall I am trying to accomplish is that Content editors, site managers, and other DNN login roles like admin/host - it is often VERY helpful to see the module's title when in Edit Mode as it can provide key info about what is what on the page and how it works.
 
Since modern DNN adds class="dnnEditState" to the <body> tag, maybe there is a simple way to make sure the module Title is visible in Edit mode only? There are other ways to Boolean detect whether or not the user is viewing in edit mode both in JavaScript on the client-side as well as server-side. Maybe we just need something that works akin to how we recently brought back the missing Pane names?
